"""Alaska Artifact Service — test suite (stdlib only, no live network).

Covers: DocFlow validation, DOCX-from-model, DOCX template-fill (scalar tokens +
table-row expansion), placeholder/forbidden-substring guards, the validate_docx
delivery gate, filesystem-JSON storage (+ overwrite protection + metadata), the
text PDF writer, and Slack upload with a fake transport (success + failure paths).

Run: python3 -m pytest tests/test_alaska_artifacts.py -q
"""
from __future__ import annotations

import json
import os
import re
import sys
import tempfile
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "lib"))

import alaska_artifacts as A  # noqa: E402
from alaska_artifacts import docflow, docx, pdf, slack_upload, store  # noqa: E402

_W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def _tmp() -> Path:
    return Path(tempfile.mkdtemp(prefix="alaska_artifacts_test_"))


def _docx_text(path) -> str:
    xml = zipfile.ZipFile(path).read("word/document.xml")
    root = ET.fromstring(xml)
    return "\n".join(t.text or "" for t in root.iter(_W + "t"))


def _raises(exc_types, fn, *args, **kwargs):
    try:
        fn(*args, **kwargs)
    except exc_types as exc:
        return exc
    raise AssertionError("expected %s to be raised" % (exc_types,))


def _kitchen_sink_spec() -> dict:
    return {
        "meta": {"title": "Weekly Digest", "subtitle": "BON Credit", "author": "Alaska",
                 "date": "2026-06-05", "format": "letter"},
        "options": {"accent_color": "1F4E79", "font": "Calibri"},
        "blocks": [
            {"type": "heading", "level": 1, "text": "Summary"},
            {"type": "paragraph", "text": "Shipped 4 tasks this week."},
            {"type": "bullets", "items": ["First item", "Second item"]},
            {"type": "numbered", "items": ["Step one", "Step two"]},
            {"type": "table", "title": "Owners", "columns": ["Name", "Tasks"],
             "rows": [["Sandeep", "2"], ["Pankaj", "3"]], "align": ["left", "right"]},
            {"type": "callout", "style": "warning", "text": "One blocker is overdue."},
            {"type": "spacer"},
            {"type": "pagebreak"},
            {"type": "heading", "level": 2, "text": "Appendix"},
            {"type": "paragraph", "text": "Generated by the Alaska Artifact Service."},
        ],
    }


# --------------------------------------------------------------------------
# DocFlow validation
# --------------------------------------------------------------------------

def test_validate_docflow_accepts_kitchen_sink():
    assert docflow.validate_docflow(_kitchen_sink_spec()) == []


def test_validate_docflow_reports_problems():
    assert "meta.title is required" in docflow.validate_docflow({"meta": {}, "blocks": []})
    bad_block = {"meta": {"title": "T"}, "blocks": [{"type": "nope"}]}
    assert any("not in" in e for e in docflow.validate_docflow(bad_block))
    bad_table = {"meta": {"title": "T"}, "blocks": [
        {"type": "table", "columns": ["A", "B"], "rows": [["only-one"]]}]}
    assert any("expected 2" in e for e in docflow.validate_docflow(bad_table))


# --------------------------------------------------------------------------
# DOCX from structured model
# --------------------------------------------------------------------------

def test_render_docx_from_docflow_is_valid():
    out = _tmp() / "digest.docx"
    res = A.render_docx_from_docflow(_kitchen_sink_spec(), str(out))
    assert out.exists() and res["bytes"] > 0
    assert "word/document.xml" in res["parts"]
    # The delivery gate passes: valid zip, required parts, well-formed XML, no placeholders.
    gate = A.validate_docx(str(out))
    assert gate["ok"] is True, gate["errors"]
    text = _docx_text(out)
    assert "Summary" in text and "Sandeep" in text and "WARNING" in text


def test_render_docx_from_docflow_rejects_invalid_spec():
    out = _tmp() / "bad.docx"
    err = _raises(docx.DocflowValidationError, A.render_docx_from_docflow,
                  {"meta": {}, "blocks": []}, str(out))
    assert err.errors
    assert not out.exists()  # nothing written on invalid spec


# --------------------------------------------------------------------------
# DOCX template fill — scalar tokens
# --------------------------------------------------------------------------

def _make_template(blocks, dirpath) -> str:
    spec = {"meta": {"title": "Internal Report"}, "blocks": blocks}
    tpl = str(Path(dirpath) / "template.docx")
    A.render_docx_from_docflow(spec, tpl)
    return tpl


def test_template_fill_replaces_scalar_tokens():
    d = _tmp()
    tpl = _make_template([
        {"type": "paragraph", "text": "User: {{user_id}}"},
        {"type": "paragraph", "text": "Name: {{first_name}}"},
    ], d)
    out = str(d / "filled.docx")
    res = A.render_docx_from_template(
        tpl, {"{{user_id}}": "1414", "{{first_name}}": "Sandeep"}, out)
    assert res["replaced_keys"] == ["{{first_name}}", "{{user_id}}"]
    text = _docx_text(out)
    assert "1414" in text and "Sandeep" in text
    assert "{{" not in text
    assert A.validate_docx(out)["ok"] is True


def test_template_fill_unfilled_placeholder_fails_loudly():
    d = _tmp()
    tpl = _make_template([{"type": "paragraph", "text": "Owed: {{balance}}"}], d)
    out = str(d / "filled.docx")
    # We provide nothing for {{balance}} -> the post-fill guard must raise.
    err = _raises(docx.TemplateRenderError, A.render_docx_from_template, tpl, {}, out)
    assert "placeholder" in str(err).lower()


def test_template_fill_unknown_bracket_behavior_is_defined():
    d = _tmp()
    tpl = _make_template([{"type": "paragraph", "text": "See Appendix A for detail."}], d)
    # Inject a literal bracket token by filling a known token into a bracket form.
    tpl2 = _make_template([{"type": "paragraph", "text": "Ref {{ref}}"}], d)
    out = str(d / "with_bracket.docx")
    # Default: a leftover [bracket] placeholder is rejected.
    A.render_docx_from_template(tpl2, {"{{ref}}": "[Appendix A]"}, out,
                                forbid_placeholder_patterns=())  # we WANT the bracket in
    assert "[Appendix A]" in _docx_text(out)
    # And with the default guard on, the same content fails the validate gate.
    leftovers = A.validate_docx_no_placeholders(out)
    assert "[Appendix A]" in leftovers


def test_template_fill_forbids_substrings():
    d = _tmp()
    tpl = _make_template([{"type": "paragraph", "text": "Note {{n}}"}], d)
    out = str(d / "emdash.docx")
    err = _raises(docx.TemplateRenderError, A.render_docx_from_template,
                  tpl, {"{{n}}": "a—b"}, out, forbid_substrings=("—",))
    assert "forbidden" in str(err).lower()


# --------------------------------------------------------------------------
# DOCX template fill — table row expansion
# --------------------------------------------------------------------------

def test_template_fill_expands_table_rows():
    d = _tmp()
    tpl = _make_template([
        {"type": "table", "columns": ["Account", "Balance"], "rows": [["{{a}}", "{{b}}"]]},
    ], d)
    out = str(d / "accounts.docx")
    res = A.render_docx_from_template(
        tpl, {}, out,
        table_fills=[{"locate": "Account", "rows": [["Visa", "$100"], ["Amex", "$200"]]}])
    assert res["table_fills"] == ["Account"]
    text = _docx_text(out)
    assert "Visa" in text and "Amex" in text and "$200" in text
    assert "{{" not in text
    assert A.validate_docx(out)["ok"] is True


def test_template_fill_table_missing_prototype_raises():
    d = _tmp()
    # A table with a header row but no data row to clone.
    tpl = _make_template([{"type": "table", "columns": ["Only", "Header"], "rows": []}], d)
    out = str(d / "x.docx")
    _raises(docx.TemplateRenderError, A.render_docx_from_template, tpl, {}, out,
            table_fills=[{"locate": "Only", "rows": [["1", "2"]]}])


# --------------------------------------------------------------------------
# validate_docx gate — failure modes
# --------------------------------------------------------------------------

def test_validate_docx_catches_bad_zip():
    d = _tmp()
    p = d / "not.docx"
    p.write_text("this is not a zip", encoding="utf-8")
    res = A.validate_docx(str(p))
    assert res["ok"] is False and "bad_zip" in res["errors"]


def test_validate_docx_catches_missing_parts():
    d = _tmp()
    p = str(d / "incomplete.docx")
    with zipfile.ZipFile(p, "w") as zf:
        zf.writestr("[Content_Types].xml", "<Types/>")  # no word/document.xml
    res = A.validate_docx(p)
    assert res["ok"] is False
    assert any("missing_parts" in e for e in res["errors"])


def test_validate_docx_no_placeholders_lists_leftovers():
    d = _tmp()
    tpl = _make_template([{"type": "paragraph", "text": "Owner {{owner}} and [TBD]"}], d)
    leftovers = A.validate_docx_no_placeholders(tpl)
    assert "{{owner}}" in leftovers and "[TBD]" in leftovers


# --------------------------------------------------------------------------
# storage (filesystem JSON, no DB)
# --------------------------------------------------------------------------

def test_store_artifact_writes_file_and_metadata():
    d = _tmp()
    base = str(d / "store")
    src = str(d / "report.docx")
    A.render_docx_from_docflow(_kitchen_sink_spec(), src)

    meta = A.store_artifact(src, "docx", "weekly-digest", "2026-06-05", base_dir=base)
    assert meta["artifact_id"] == "weekly-digest/2026-06-05/report.docx"
    assert os.path.exists(meta["path"])
    assert os.path.exists(meta["path"] + ".meta.json")
    assert os.path.exists(src)  # source preserved (copy, not move)
    assert meta["bytes"] > 0 and len(meta["sha256"]) == 64
    assert meta["created_at"]

    # round-trip via get_artifact_metadata
    loaded = A.get_artifact_metadata(meta["artifact_id"], base_dir=base)
    assert loaded == meta
    # index has the row
    rows = A.list_artifacts("weekly-digest", base_dir=base)
    assert len(rows) == 1 and rows[0]["artifact_id"] == meta["artifact_id"]


def test_store_artifact_no_overwrite_unless_requested():
    d = _tmp()
    base = str(d / "store")
    src = str(d / "report.docx")
    A.render_docx_from_docflow(_kitchen_sink_spec(), src)
    A.store_artifact(src, "docx", "audit", "1414", base_dir=base)
    # Second store of the same owner/run/name must refuse by default.
    _raises(store.ArtifactExistsError, A.store_artifact, src, "docx", "audit", "1414", base_dir=base)
    # ...unless overwrite is explicit.
    meta = A.store_artifact(src, "docx", "audit", "1414", base_dir=base, overwrite=True)
    assert meta["artifact_id"] == "audit/1414/report.docx"


def test_store_artifact_sanitizes_path_segments():
    d = _tmp()
    base = str(d / "store")
    src = str(d / "r.docx")
    A.render_docx_from_docflow(_kitchen_sink_spec(), src)
    meta = A.store_artifact(src, "docx", "../etc", "a/b", base_dir=base)
    # No path traversal escapes the base dir.
    assert os.path.normpath(meta["path"]).startswith(os.path.normpath(base) + os.sep)


def test_artifacts_base_env_override():
    d = _tmp()
    prev = os.environ.get("ALASKA_ARTIFACTS_DIR")
    os.environ["ALASKA_ARTIFACTS_DIR"] = str(d / "viaenv")
    try:
        assert store.artifacts_base() == str(d / "viaenv")
    finally:
        if prev is None:
            os.environ.pop("ALASKA_ARTIFACTS_DIR", None)
        else:
            os.environ["ALASKA_ARTIFACTS_DIR"] = prev


# --------------------------------------------------------------------------
# PDF (text-only, stdlib)
# --------------------------------------------------------------------------

def test_render_pdf_from_docflow_is_valid():
    out = _tmp() / "digest.pdf"
    res = A.render_pdf_from_docflow(_kitchen_sink_spec(), str(out))
    assert out.exists() and res["bytes"] > 0 and res["pages"] >= 2  # pagebreak -> >=2
    gate = A.validate_pdf(str(out))
    assert gate["ok"] is True, gate["errors"]
    head = out.read_bytes()[:8]
    assert head.startswith(b"%PDF-")


# --------------------------------------------------------------------------
# Slack upload (fake transport)
# --------------------------------------------------------------------------

class _FakeSlack:
    def __init__(self, responses):
        self.responses = responses
        self.calls = []
        self._i = 0

    def __call__(self, method, url, *, headers=None, body=None, timeout=None):
        self.calls.append({"method": method, "url": url, "headers": headers, "body": body})
        resp = self.responses[self._i]
        self._i += 1
        return resp


def _a_file() -> str:
    d = _tmp()
    src = str(d / "report.docx")
    A.render_docx_from_docflow(_kitchen_sink_spec(), src)
    return src


def test_slack_upload_success_runs_three_step_flow():
    fake = _FakeSlack([
        (200, json.dumps({"ok": True, "upload_url": "https://upload.example/abc",
                          "file_id": "F123"}).encode()),
        (200, b""),  # PUT bytes
        (200, json.dumps({"ok": True}).encode()),  # complete
    ])
    res = A.upload_artifact_to_slack(_a_file(), "C42", token="xoxb-test", http_request=fake)
    assert res["ok"] is True and res["file_id"] == "F123"
    assert len(fake.calls) == 3
    assert fake.calls[0]["url"] == slack_upload.GET_UPLOAD_URL
    assert fake.calls[1]["url"] == "https://upload.example/abc"
    assert fake.calls[2]["url"] == slack_upload.COMPLETE_UPLOAD_URL


def test_slack_upload_failure_preserves_file():
    path = _a_file()
    fake = _FakeSlack([(200, json.dumps({"ok": False, "error": "channel_not_found"}).encode())])
    res = A.upload_artifact_to_slack(path, "C42", token="xoxb-test", http_request=fake)
    assert res["ok"] is False and res["step"] == "get_upload_url"
    assert os.path.exists(path)  # artifact is never deleted on failure


def test_slack_upload_missing_file_is_reported_not_raised():
    fake = _FakeSlack([])
    res = A.upload_artifact_to_slack("/no/such/file.docx", "C42", token="xoxb-test", http_request=fake)
    assert res["ok"] is False and res["step"] == "read"


# --------------------------------------------------------------------------
# isolation guard — never import V5 pmf_os or the audit skill at runtime
# --------------------------------------------------------------------------

def test_artifact_modules_do_not_import_workstream_code():
    pkg = REPO_ROOT / "lib" / "alaska_artifacts"
    forbidden = re.compile(r"^(import|from)\s+(lib\.)?(pmf_os|audit_[a-z]+|bon_internal)")
    for pyfile in pkg.glob("*.py"):
        for line in pyfile.read_text(encoding="utf-8").splitlines():
            assert not forbidden.match(line.strip()), "%s imports workstream code: %s" % (pyfile.name, line)


def test_public_api_is_exported():
    for name in ("render_docx_from_docflow", "render_docx_from_template", "validate_docx",
                 "store_artifact", "get_artifact_metadata", "upload_artifact_to_slack",
                 "render_pdf_from_docflow"):
        assert hasattr(A, name), name
