"""audit_render — fill the Internal Report DOCX template from the audit JSON.

Stdlib ONLY (zipfile + xml.etree.ElementTree). No python-docx, no template
engine, no V5 code. The deployed OpenClaw image is deliberately slim (no
office/PDF render packages), so this keeps the dependency footprint at zero.

A .docx is a zip of XML. We rewrite word/document.xml in place and copy every
other part (styles, header, footer, fonts) untouched, so the template's exact
styling is preserved. The template's tokens are clean single <w:t> runs, which
makes scalar replacement and table-row cloning straightforward.

render_docx(audit, template_path, out_path) -> out_path
Raises AuditValidationError if the audit fails the skill's gate (never renders
a bad report). Raises AuditRenderError if any placeholder survives the fill.
"""
from __future__ import annotations

import copy
import os
import re
import xml.etree.ElementTree as ET
import zipfile
from typing import List, Optional

import audit_validate

W = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
XML_SPACE = "{http://www.w3.org/XML/1998/namespace}space"

# Every distinct bracket token the template ships with. After a successful
# fill, NONE of these may remain (final guard).
TEMPLATE_PLACEHOLDERS = [
    "[Write here]", "[MM/DD/YYYY]", "[Your Name]", "[User ID]", "[First Name]",
    "[Score]", "[Poor/Fair/Good/Excellent]", "[CR Only / CR + Card / CR + Card + Bank]",
    "[Name]", "[CC/Auto/Student/etc]", "[X]", "[Y]", "[Open/Collections/etc]",
    "[type]", "[Estimate/Exact]", "[Low/Med/High]", "[band]",
]

LINK_PITCH_NULL_TEXT = "N/A, card and bank already linked."


class AuditValidationError(Exception):
    def __init__(self, failures):
        self.failures = failures
        super().__init__("audit failed validation: %s" % failures)


class AuditRenderError(Exception):
    pass


# --------------------------------------------------------------------------
# small XML helpers
# --------------------------------------------------------------------------

def _cell_text(tc) -> str:
    return "".join(t.text or "" for t in tc.iter(W + "t")).strip()


def _row_text(tr) -> str:
    return " ".join(t.text or "" for t in tr.iter(W + "t"))


def _set_cell_text(tc, text: str) -> None:
    ts = list(tc.iter(W + "t"))
    if ts:
        ts[0].text = text
        ts[0].set(XML_SPACE, "preserve")
        for extra in ts[1:]:
            extra.text = ""
    else:  # cell with no run -> attach one to the first paragraph
        p = tc.find(W + "p")
        if p is None:
            p = ET.SubElement(tc, W + "p")
        r = ET.SubElement(p, W + "r")
        t = ET.SubElement(r, W + "t")
        t.set(XML_SPACE, "preserve")
        t.text = text


def _cells(tr) -> List:
    return tr.findall(W + "tc")


def _rows(tbl) -> List:
    return tbl.findall(W + "tr")


def _money(v) -> str:
    try:
        return "${:,.2f}".format(float(v))
    except (TypeError, ValueError):
        return "Not reported"


def _register_namespaces(xml_bytes: bytes) -> None:
    head = xml_bytes[:3000].decode("utf-8", "replace")
    for prefix, uri in re.findall(r'xmlns:([A-Za-z0-9]+)="([^"]+)"', head):
        ET.register_namespace(prefix, uri)
    m = re.search(r'xmlns="([^"]+)"', head)
    if m:
        ET.register_namespace("", m.group(1))


def _make_marking() -> ET.Element:
    p = ET.Element(W + "p")
    r = ET.SubElement(p, W + "r")
    rpr = ET.SubElement(r, W + "rPr")
    ET.SubElement(rpr, W + "b")
    ET.SubElement(rpr, W + "color").set(W + "val", "C00000")
    t = ET.SubElement(r, W + "t")
    t.set(XML_SPACE, "preserve")
    t.text = "INTERNAL CONFIDENTIAL. Generated by Alaska. Do not share externally."
    return p


# --------------------------------------------------------------------------
# table location (by header content, order-independent)
# --------------------------------------------------------------------------

def _find_tables(root):
    tables = {"user": None, "accounts": None, "calc": None, "opps": None}
    for tbl in root.iter(W + "tbl"):
        header = _row_text(_rows(tbl)[0]) if _rows(tbl) else ""
        low = header.lower()
        if "audit date" in low:
            tables["user"] = tbl
        elif "est. monthly interest" in low or "util %" in low:
            tables["accounts"] = tbl
        elif "estimated apr used" in low or _cell_text(_cells(_rows(tbl)[0])[0]).lower().startswith("estimated apr"):
            tables["calc"] = tbl
        elif "opportunity type" in low:
            tables["opps"] = tbl
    return tables


def _replace_data_rows(tbl, fill_fns) -> None:
    """Keep the header row, drop every other row, then clone the first data row
    once per fill_fn and fill it. Preserves cell styling from the prototype."""
    trs = _rows(tbl)
    header, prototype = trs[0], trs[1]
    for tr in trs[1:]:
        tbl.remove(tr)
    pos = list(tbl).index(header) + 1
    for i, fn in enumerate(fill_fns):
        clone = copy.deepcopy(prototype)
        fn(clone)
        tbl.insert(pos + i, clone)


# --------------------------------------------------------------------------
# section fillers
# --------------------------------------------------------------------------

def _fill_user_overview(tbl, audit) -> None:
    meta, user = audit.get("audit_meta", {}), audit.get("user", {})
    token_map = {
        "[MM/DD/YYYY]": str(meta.get("audit_date", "")),
        "[Your Name]": "Alaska (automated audit)",
        "[User ID]": str(meta.get("user_id", "")),
        "[First Name]": str(user.get("first_name", "")),
        "[Score]": str(user.get("credit_score", "")),
        "[Poor/Fair/Good/Excellent]": str(user.get("score_band", "")),
        "[CR Only / CR + Card / CR + Card + Bank]": str(meta.get("data_available", "")),
    }
    for t in tbl.iter(W + "t"):
        key = (t.text or "").strip()
        if key in token_map:
            t.text = token_map[key]


def _fill_accounts(tbl, accounts) -> None:
    def make_fn(acc):
        def fn(row):
            cells = _cells(row)
            util = acc.get("utilization_pct")
            vals = [
                str(acc.get("name", "")),
                str(acc.get("type", "")),
                _money(acc.get("balance")),
                _money(acc.get("limit")) if acc.get("limit") is not None else "Not reported",
                ("{:.1f}%".format(util) if util is not None else "N/A"),
                str(acc.get("status", "")),
                _money(acc.get("est_monthly_interest")),
            ]
            for cell, val in zip(cells, vals):
                _set_cell_text(cell, val)
        return fn
    _replace_data_rows(tbl, [make_fn(a) for a in accounts])


def _fill_calculations(tbl, calc) -> None:
    for tr in _rows(tbl):
        cells = _cells(tr)
        if len(cells) < 2:
            continue
        label = _cell_text(cells[0]).lower()
        if "apr" in label:
            val = str(calc.get("apr_estimation_basis", "Not available"))
        elif "monthly interest" in label:
            val = "~%s/month" % _money(calc.get("total_monthly_interest_est"))
        elif "yearly interest" in label:
            val = "~%s/year" % _money(calc.get("total_yearly_interest_est"))
        elif "overall utilization" in label:
            val = "%s%% overall; %s%% on cards with balances" % (
                calc.get("overall_utilization_pct"), calc.get("utilization_on_cards_with_balance_pct"))
        elif "collections total" in label:
            val = str(calc.get("collections_total", "None"))
            if calc.get("collections_count"):
                val = "%s across %s accounts" % (_money(calc.get("collections_total")), calc.get("collections_count"))
        elif "collections score" in label:
            val = str(calc.get("collections_score_cost_est", "None"))
        else:
            val = None
        if val is not None:
            _set_cell_text(cells[1], val)
        # belt-and-suspenders: never leave a [X]/[band] token in a value cell
        if "[" in _cell_text(cells[1]):
            _set_cell_text(cells[1], "Not available")


def _fill_opportunities(tbl, opps) -> None:
    effort_label = {1: "Low", 2: "Med", 3: "High"}

    def make_fn(opp):
        def fn(row):
            cells = _cells(row)
            confidence = "Exact" if opp.get("confidence_multiplier", 0) >= 1.0 else "Estimate"
            vals = [
                str(opp.get("rank", "")),
                str(opp.get("type", "")),
                "%s/mo (%s/yr)" % (_money(opp.get("monthly_savings")), _money(opp.get("yearly_savings"))),
                confidence,
                effort_label.get(opp.get("effort_score"), str(opp.get("effort_score", ""))),
                "%g" % opp.get("priority_score", 0),
            ]
            for cell, val in zip(cells, vals):
                _set_cell_text(cell, val)
        return fn
    _replace_data_rows(tbl, [make_fn(o) for o in opps])


def _flowchart_contents(audit) -> List[str]:
    f = audit.get("flowchart", {})

    def link(v):
        return str(v) if v not in (None, "") else LINK_PITCH_NULL_TEXT

    buttons = f.get("step_5_buttons", []) or []
    buttons_txt = "   ".join("%d) %s" % (i + 1, b) for i, b in enumerate(buttons))
    task = f.get("step_11_task", {}) or {}
    followup = f.get("step_13_followup", {}) or {}
    notes = audit.get("notes_edge_cases", []) or []
    open_q = audit.get("open_questions", []) or []
    notes_block = " | ".join(str(n) for n in notes)
    if open_q:
        notes_block += "    Open questions: " + " | ".join(str(q) for q in open_q)

    return [
        str(f.get("step_1_data_ingestion", "")),
        str(f.get("step_2_calculations", "")),
        str(f.get("step_3_rank_and_decide", "")),
        str(f.get("step_4_opening_message", "")),
        buttons_txt,
        str(f.get("step_6_button_1_response", "")),
        str(f.get("step_7_button_2_response", "")),
        str(f.get("step_8_button_3_response", "")),
        str(f.get("step_9_not_interested", "")),
        str(f.get("step_10_off_script", "")),
        "Task: %s. Saves %s." % (task.get("title", ""), task.get("dollar_value", "")),
        str(f.get("step_12_detection", "")),
        "Day 7: %s    Day 14: %s" % (followup.get("day_7", ""), followup.get("day_14", "")),
        link(f.get("step_14_link_pitch_trigger")),
        link(f.get("step_15_link_pitch_text")),
        notes_block,  # 16th [Write here] is the Notes & Edge Cases section
    ]


def _fill_write_here_blocks(root, contents: List[str]) -> None:
    runs = [t for t in root.iter(W + "t") if (t.text or "").strip() == "[Write here]"]
    if len(runs) != len(contents):
        raise AuditRenderError(
            "template has %d '[Write here]' blocks but the audit supplies %d sections; "
            "the template may have changed" % (len(runs), len(contents)))
    for run, content in zip(runs, contents):
        run.text = content
        run.set(XML_SPACE, "preserve")


def _fix_template_caption(root) -> None:
    """The template caption says 'Rank by yearly dollar impact' which contradicts
    the skill (rank by priority score). Correct it so the report is self-consistent."""
    for t in root.iter(W + "t"):
        if t.text and "Rank by yearly dollar impact" in t.text:
            t.text = "Ranked by priority score (savings x confidence / effort), highest first. This determines what the agent leads with."


# --------------------------------------------------------------------------
# entrypoint
# --------------------------------------------------------------------------

def render_docx(audit: dict, template_path: str, out_path: str) -> str:
    result = audit_validate.validate_audit(audit)
    if not result["ok"]:
        raise AuditValidationError(result["failures"])

    with zipfile.ZipFile(template_path) as zin:
        names = zin.namelist()
        members = {n: zin.read(n) for n in names}

    doc_xml = members["word/document.xml"]
    _register_namespaces(doc_xml)
    root = ET.fromstring(doc_xml)
    body = root.find(W + "body")

    tables = _find_tables(root)
    if tables["user"] is not None:
        _fill_user_overview(tables["user"], audit)
    if tables["accounts"] is not None:
        _fill_accounts(tables["accounts"], audit.get("accounts", []))
    if tables["calc"] is not None:
        _fill_calculations(tables["calc"], audit.get("calculations", {}))
    if tables["opps"] is not None:
        _fill_opportunities(tables["opps"], audit.get("opportunities", []))

    _fix_template_caption(root)
    _fill_write_here_blocks(root, _flowchart_contents(audit))

    if body is not None:
        body.insert(0, _make_marking())

    new_doc = b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n' + \
        ET.tostring(root, encoding="unicode").encode("utf-8")

    # Final guard: never emit a report with a surviving placeholder.
    rendered_text = "\n".join(t.text or "" for t in root.iter(W + "t"))
    leftover = [p for p in TEMPLATE_PLACEHOLDERS if p in rendered_text]
    if leftover:
        raise AuditRenderError("unfilled placeholders remain: %s" % leftover)
    if "—" in rendered_text:
        raise AuditRenderError("rendered document contains an em dash")

    parent = os.path.dirname(out_path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zout:
        for n in names:
            zout.writestr(n, new_doc if n == "word/document.xml" else members[n])
    try:
        os.chmod(out_path, 0o600)
    except OSError:
        pass
    return out_path
